# 基于 Python 镜像构建后端应用
FROM python:3.9-slim

# 设置工作目录
WORKDIR /backend

# 复制 Flask 应用代码到容器
COPY . .

# 安装 Flask 和 MySQL 客户端依赖
RUN pip install Flask flask-mysql

# 暴露端口
EXPOSE 5000

# 启动 Flask 应用
CMD ["python"]
